In [1]:
import torch
import torch.nn as nn


In [2]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out

In [3]:
## making a simple neural network of one layer


features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)


tensor([[0.4454],
        [0.4429],
        [0.4006],
        [0.4351],
        [0.4891],
        [0.4987],
        [0.4918],
        [0.4201],
        [0.4524],
        [0.4515]], grad_fn=<SigmoidBackward0>)

In [12]:
model.sigmoid

Sigmoid()

## now we will try to make a neural network with 2 hidden layers where first layer will contain 5 nodes and second layer will contain 3 nodes

In [13]:
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,5)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(5,1)
    self.sigmoid=nn.Sigmoid()

  def forward (self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out

In [14]:
## create a random dataset
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.4190],
        [0.4258],
        [0.4239],
        [0.4232],
        [0.4298],
        [0.4128],
        [0.4348],
        [0.4026],
        [0.4059],
        [0.4114]], grad_fn=<SigmoidBackward0>)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2365, -0.3139, -0.1187,  0.0158,  0.0582],
        [ 0.4021,  0.1446,  0.4252,  0.1329, -0.0256],
        [-0.2186,  0.2455, -0.1930, -0.3668, -0.2741],
        [-0.1585, -0.1658, -0.3631, -0.0788,  0.2982],
        [ 0.0307, -0.4165,  0.0561, -0.1241, -0.0270]], requires_grad=True)

In [16]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0221, -0.2320, -0.1604,  0.0246,  0.3164]], requires_grad=True)

In [17]:
pip install torchinfo

In [18]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 5]                   30
├─ReLU: 1-2                              [10, 5]                   --
├─Linear: 1-3                            [10, 1]                   6
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 36
Trainable params: 36
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## using sequential containers to optimise the code

In [19]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,5),
        nn.ReLU(),
        nn.Linear(5,1),
        nn.Sigmoid()
    )

  def forward (self,features):
    out=self.network(features)

    return out

In [20]:
## create a random dataset
features=torch.rand(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5325],
        [0.5361],
        [0.5351],
        [0.5365],
        [0.5345],
        [0.5321],
        [0.5345],
        [0.5324],
        [0.5329],
        [0.5354]], grad_fn=<SigmoidBackward0>)